### ISSUE TITLE
verify checkbox & radio button answers are rendered in the generated PDF

### ISSUE THREAD

**Issue by kelseyq** [SexualHealthInnovations/callisto-core#122]
current symbols being used make this tricky--see #119 
Open to changing symbols to make testing easier

**Comment by keisetsu** [comment]
The reason this is difficult is because the PageObject.extractText function in PyPDF2 returns regular ASCII-looking characters for encoded character from unicode: for example, it shows 'n' for what was u'2610', the empty checkbox character.

I've traced this all the way back to python's own zlib decode function (ie, as far as I can tell this is not PyPDF2's fault), at the point where PyPDF2 takes the "Contents" data stream and [decodes](https://github.com/mstamy2/PyPDF2/blob/master/PyPDF2/filters.py#L51) it.

It could be that somehow reportlab is messing things up when encoding, but the characters show up correctly in my pdf reader and in pdftotext on linux.
Perhaps call pdftotext? I guess that would only work in a linux environment.

**Comment by keisetsu** [comment]
What would you think about creating tables for the questions and answers, with just `x`s or something similar to designate the chosen answers? It'll complicate the rendering code, but it might also help with #34. I'll try to put together an example.

**Comment by keisetsu** [comment]
Spent some time trying to find a solution:
I've dug pretty deep into PyPDF2, as mentioned above, and I haven't been able to find a way to read these unicode characters.
I've also looked into pdfrw, otherwise a great library, but doesn't seem to extract text
pdfquery also looked good, but I get the same results for the unicode characters.

There are three poppler (a c library for pdfs, used by the pdftotext utility mentioned above) binding libraries (pypoppler, python-poppler-qt4 and -5), but I have not been able to get them to compile, and they may be dependent on linux.

**Comment by divergentdave** [comment]
The check boxes are indeed stored as the character "n" in the PDF, though they are shown in a different PDF font than the rest of the document, and they get remapped back to the correct Unicode codepoints when you copy them to the clipboard. (presumably because the font uses /ZapfDingbatsEncoding, see the PDF standard or [this table](ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/ADOBE/zdingbat.txt)) According to the Zapf Dingbats table, 'n' or '\156' maps to ■, and '7' or '\067' maps to ✗, our other symbol. (FYI I used [iText RUPS](https://github.com/itext/rups) to dig into this.)

```
BT
1 0 0 1 42 5 Tm
/F4 12 Tf
14.4 TL
(n) Tj
/F1 12 Tf
14.4 TL
T*
ET
Q
q
1 0 0 1 138 491 cm
q
0 0 0 rg
BT
1 0 0 1 0 3 Tm
/F1 14 Tf
17 TL
(This is choice 3) Tj
T*
ET
```

The upshot is, we can reproducibly identify checks and boxes, though [the PyPDF2 documentation](https://pythonhosted.org/PyPDF2/PageObject.html#PyPDF2.pdf.PageObject.extractText) warns "Do not rely on the order of text coming out of this function, as it will change if this function is made more sophisticated." For now, the text comes out in a natural order, so I think we should write the text to expect "n" and "7". If PyPDF2 starts handling the encoding, or changes order of text output, we can look at doing something more sophisticated then. I'll draft a PR for such a test case.

**Comment by divergentdave** [comment]
Oops, GitHub doesn't like FTP links. The Zapf Dingbats encoding table is at ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/ADOBE/zdingbat.txt or table D.5 in the PDF standard.
