### ISSUE TITLE
List dependencies in README

### ISSUE THREAD

**Issue by non** [SexualHealthInnovations/callisto-core#7]
It would be nice to know which versions of Python/Django/other libraries are needed.

**Comment by kevindaum** [comment]
Would requirements.txt not be the right place for this?

**Comment by non** [comment]
Yes, I think that does make sense -- although it would also be nice to have an overview in the README, especially since there may be dependencies outside of Python (e.g. database provider).

**Comment by kevindaum** [comment]
Oh, right. It looks like this isn't a self-contained project, which might explain why there aren't any requirements defined. There aren't any `URLConf`s and no settings file(s), for example, which is where you'd see the database configuration. That's probably why @kelseyq created #3. But since this is a collection of django apps, at a minimum we need to know what version of django was used. It would also be helpful to know what version(s) of python are supported. It looks like there are other dependencies, too, though, such as `bugsnag`, `ratelimit`, `gnupg`, etc.

**Comment by kelseyq** [comment]
you caught me--I didn't finish packaging these apps before we flipped the switch to make it public! stay tuned ;)

**Comment by kevindaum** [comment]
Okay!

**Comment by kelseyq** [comment]
Should be good now with #11 and #35.
